[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32G071GBUx"
# runner = "arm-none-eabi-gdb -q"

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x"
]

[build]
target = "thumbv6m-none-eabi"